[features]
seeds = false
[programs.localnet]
simple_vote = "4gsCCCy3Njzmf1QNGz3P6GyPEtZnRftDCQjnpnVTtDjT"
election = "DXakT9aCTCSak2gxKKaddyVLGJBNhUf13nfz94gXjsNJ"
staker = "HQYiW7oWUMX4WMBdHVZM5gZNVwz7Sbg4sv59ZWREGKEY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/freebird0323/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
