# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  formatting:
    docker:
      - image: glacialengineering/solana-build:0.21.0.1
    steps:
      - checkout
      - run:
          name: "Format rust code"
          command: "cargo fmt --all -- --check"
      - run:
          name: "Check rust code"
          command: "cargo clippy -- -D warnings --warn clippy::all"
  security-check:
    docker:
      - image: glacialengineering/solana-build:0.21.0.1
    steps:
      - checkout
      # - run:
      #     name: "Soteria analysis"
      #     command: "cd programs/`ls programs/` && soteria -analyzeAll ."
      - run:
          name: "Cargo audit"
          command: "cargo audit"
  test:
    docker:
      - image: glacialengineering/solana-build:0.21.0.1
    steps:
      - checkout
      - run:
          name: "Unit tests"
          command: "cargo test --lib"
      - run:
          name: "Anchor tests"
          command: |
            solana-keygen new -s --no-bip39-passphrase
            npm install
            anchor test -- --features local-testing,test-id
      - store_artifacts:
          path: /root/project/.anchor/program-logs
          destination: program-logs
  build:
    docker:
      - image: glacialengineering/solana-build:0.21.0.1
    steps:
      - checkout
      - run:
          name: "Build program"
          command: "anchor build && rm ./target/deploy/*.json && cd ./target/deploy && sha256sum * > sha256.txt"
      - store_artifacts:
          path: /root/project/target/deploy
          destination: bpf-programs
      - store_artifacts:
          path: /root/project/target/idl
          destination: idls
      - store_artifacts:
          path: /root/project/target/types
          destination: types
  deploy-devnet:
    docker:
      - image: glacialengineering/solana-build:0.21.0.1
    steps:
      - checkout
      - run:
          name: "Deploy"
          command: |
            echo "$SOLANA_DEV_PROGRAM_KEY" > program-key.json
            echo "$SOLANA_DEV_AUTHORITY_KEY" > auth-key.json
            anchor build -- --features test-id
            export PGM=`ls ./target/deploy/*.so`
            echo "deploying $PGM"
            solana program deploy -u d -k ./auth-key.json --program-id ./program-key.json $PGM

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
    test:
    
